### ISSUE TITLE
env\scripts\activate.bat is missing

### ISSUE THREAD

**Issue by bizarreWizard** [Azure/azure-cli-dev-tools#103]
The env folder is not properly generated by command "python3 -m venv env"

I use Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32:

C:\Users>cd ..

C:\>cd azure-cli

C:\azure-cli>python3 -m venv env

C:\azure-cli>cd env

C:\azure-cli\env>cd Scripts

C:\azure-cli\env\Scripts>dir
 Volume in drive C is OSDisk
 Volume Serial Number is EA0D-AXXX

 Directory of C:\azure-cli\env\Scripts

07/01/2019  05:55 PM    <DIR>          .
07/01/2019  05:55 PM    <DIR>          ..
07/01/2019  05:55 PM           415,248 python.exe
               1 File(s)        415,248 bytes
               2 Dir(s)  335,107,608,576 bytes free

C:\azure-cli\env\Scripts>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by tjprescott** [comment]
Unfortunately, this is not an issue with azdev, but rather the Python venv command itself. StackOverflow would likely be your best resource:
https://stackoverflow.com/questions/26215790/venv-doesnt-create-activate-script-python3
