### ISSUE TITLE
pytest 5.0.1 which is incompatible for azdev 0.1.3

### ISSUE THREAD

**Issue by Juliehzl** [Azure/azure-cli-dev-tools#114]
ERROR: azdev 0.1.3 has requirement pytest~=4.4.0, but you'll have pytest 5.0.1 which is incompatible.

**Comment by tjprescott** [comment]
@Juliehzl did you try azdev 0.1.4?

**Comment by Juliehzl** [comment]
Still have an error:
ERROR: azdev 0.1.4 has requirement pytest~=4.4.0, but you'll have pytest 5.0.1 which is incompatible.

**Comment by haroldrandom** [comment]
dependency pytest now is >= 4.4.0
