### ISSUE TITLE
`azdev test vm` fails, but can succeed if testing the failed test case only

### ISSUE THREAD

**Issue by qwordy** [Azure/azure-cli-dev-tools#126]
When I run `azdev test vm`, one test case fails: `test_vm_commands.VMSSCreateLinuxSecretsScenarioTest.test_vmss_create_linux_secrets`

But if I run `azdev test test_vm_commands.VMSSCreateLinuxSecretsScenarioTest.test_vmss_create_linux_secrets`, it passes.

CI in Azure CLI can succeed.

An interesting problem.

**Comment by haroldrandom** [comment]
Can reproduce now?

**Comment by qwordy** [comment]
No. Interestingヾ(≧▽≦*)o

**Comment by haroldrandom** [comment]
I met a similar situation when I was trying to test `dns zone import`.
When run `azdev test TestDNSImport` like, I got some tests failed randomly. 
However, if I ran all the tests under this TestCase, it all passed.

Which is wired.

**Comment by qwordy** [comment]
It's time for you to show your talent and wisdom, find the cause and fix them...

**Comment by haroldrandom** [comment]
Fixed in https://github.com/Azure/azure-cli/pull/13002
