### ISSUE TITLE
azdev extension publish

### ISSUE THREAD

**Issue by zikalino** [Azure/azure-cli-dev-tools#127]
There are several crashes when publishing extension, mostly related to storage account.

For instance if users specifies storage account they don't have access to, we end up with crash, instead of nice error message. This is really difficult to debug.

**Comment by haroldrandom** [comment]
Noted. A plan will be made after Ignite.

**Comment by haroldrandom** [comment]
Guess this might help, https://github.com/Azure/azure-cli-dev-tools/pull/156, if not, feel free to reopen.
