### ISSUE TITLE
Azdev test could not work on Windows with Chinese system language

### ISSUE THREAD

**Issue by houk-ms** [Azure/azure-cli-dev-tools#203]
When running `azdev test` on a Chinese-version Windows, it will fail due to the reason [here](https://github.com/Azure/azure-cli-dev-tools/blob/master/azdev/operations/tests/__init__.py#L167).

**Comment by haroldrandom** [comment]
@houk-ms What' error exactly? Could you post a detail error output? A PR is fixing this, such that I could have a verification.

**Comment by houk-ms** [comment]
Runnning `azdev test {any mod} --discover ` on Windows with Chinese system language will reproduce the error.

**Comment by houk-ms** [comment]
I think the PR #206 will work. Close the issue now.
