### ISSUE TITLE
Fix the version of the dependent libraries

### ISSUE THREAD

**Issue by FumingZhang** [Azure/azure-cli-dev-tools#322]
Since yesterday, my CI started to report errors when using a fixed version (0.1.32) of `azdev` to setup azure-cli and the error message is something like `ModuleNotFoundError: No module named 'colorama'`.

I found the reason is `knack` removed this lib in [PR #249](https://github.com/microsoft/knack/pull/249) and so did `azdev` in [PR #321](https://github.com/Azure/azure-cli-dev-tools/pull/321). However, the version of the dependent library `knack` in `azdev`'s [setup.py](https://github.com/Azure/azure-cli-dev-tools/blob/dev/setup.py#L71) is not fixed, even if a fixed version of `azdev` is installed, the latest `knack` will still be installed through the dependencies, and the `colorama` library that the old version of `azdev` depends on is no longer installed.

I would like to ask if the maintainers could fix the version of the dependent libraries to avoid similar issues.

**Comment by jiasli** [comment]
We have removed the problematic knack: https://github.com/Azure/azure-cli/issues/20206

`azdev` didn't specify the `knack` version: https://github.com/Azure/azure-cli-dev-tools/blob/cabbb3ef6eeb398a5100f14c19d5cc3f4a8ac840/setup.py#L71

Please re-run the pipeline.

**Comment by jiasli** [comment]
We will consider pin knack version in `azdev` in the future.
