### ISSUE TITLE
Azdev cannot find my new extension to add it

### ISSUE THREAD

**Issue by Sandido** [Azure/azure-cli-dev-tools#365]
I am working in a forked repo from Azure CLI Extensions, https://github.com/Sandido/cli-magic. 
It has a new extension called Magic, and the folder and files for the extension and everything. https://github.com/Sandido/cli-magic/tree/main/src/magic

Other engineers are able to run azdev setup and add this extension no problem, but not me. 
Due to some issues and confusion in setup, I initially added the extension in a different repo during azdev setup, but then I deleted that repo and cloned a new one. 

After cloning my fork of the Azure CLI Extensions repo, and running the setup steps, when I run azdev setup, I say I am not developing a CLI module, I am developing a CLI extension, I give them the path to my forked cli extension repo, then I say I want to install an extension. I then give them the name of my extension, magic (I also tried the full path to magic). 
However, I always get the error 'cannot find the extension named magic.' But the extension is definitely there in the current repo.

**Repro:**
The specific steps I followed are (and they work for other engineers):

1. Use Azdev to setup cli extension dev environment: [Azure/azure-cli-dev-tools: Developer utilities for Azure CLI command module and extension developers. (github.com)](https://github.com/Azure/azure-cli-dev-tools)
		a. From the instructions here [Azure/azure-cli-dev-tools: Developer utilities for Azure CLI command module and extension developers. (github.com)](https://github.com/Azure/azure-cli-dev-tools)

		b. Install Python 3.6/3.7/3.8 from http://python.org/. Please note that the version of Python that comes preinstalled on OSX is 2.7. Currently it's not recommended to use Python 3.9.
		
		From <https://github.com/Azure/azure-cli-dev-tools#setting-up-your-development-environment> 
		c. install azdev using pip
			i. python -m pip install -U pip
			ii. Pip install azdev
			
		d. Fork repo [haagha/cli-magic: CLI-magic command (github.com)](https://github.com/haagha/cli-magic) and save it as C:/azure-cli-extensions
		e. Open powershell and Go into forked folder and Create a new virtual environment:
			i. Run : python -m venv env
			ii. Now activate by running:
				1) .\env\Scripts\activate.ps1
				
		
		f. Use pwshell to run Azdev setup and follow instructions:
			i. Azdev setup
			ii. Path to az cli extensions : C:/azure-cli-extensions
When asked for extensions to add : magic

**Attempted solutions:**
1. Uninstalling Azdev.
2. Using the 'azdev extension remove magic' cmd.
3. re-cloning and running through the setup seen here https://github.com/Azure/azure-cli-dev-tools over and over again. 
4. Tried adding the extension with 'azdev extension add magic' explicitly after the setup completes.

**Comment by wu5bocheng** [comment]
Hi @Sandido , your repo may be private at the moment, I can't access it and see what's going on, do you think it would be convenient to make this repo public or add viewing rights to us. Also, I would like to ask if you would try azdev extension repo list to see if your previous path was successfully deleted.

**Comment by Sandido** [comment]
@wu5bocheng , I have invited you as a collaborator to the repo. If there is a team I can add, please let me know.

**Comment by Sandido** [comment]
Looks like my old repo I deleted was still somehow saved as the extension repo! I used Remove and was able to add my extension in the new repo.
I think I'm unblocked now, am testing more now.
