### ISSUE TITLE
`azdev setup` should provide/show defaults

### ISSUE THREAD

**Issue by marstr** [Azure/azure-cli-dev-tools#37]
When setting up a new environment with `azdev setup`, you're prompted for a handful of simple questions:
```
Do you plan to develop CLI modules? (y/n):
```

```
Path (RETURN to auto-find):
```

```
Do you plan to develop CLI extensions? (y/n):
```

For the yes/no options, I'd expect that the default answer be capitalized. as: `(Y/n)` or `(y/N)`

For the location, I'd expect it to first run auto-find and show me the value that it found for inspection.

**Comment by tjprescott** [comment]
For the two questions, I'm not sure there really is a good default, so I make the user provide an answer.

It will display the CLI path that found and also seek your positive confirmation before proceeding. 
```
Path (RETURN to auto-find):
Found: D:\GitRepos\github\azure-cli

Do you plan to develop CLI extensions? (y/n): n

No problem! You can always add extension repos later with `azdev extension repo add`.

 Summary
=========

CLI: D:\GitRepos\github\azure-cli
Extension repos:
Extensions:

Proceed with installation?  (y/n):
```

**Comment by tjprescott** [comment]
For now I think it's most appropriate to force the user to make a choice rather than applying a default. If you disagree, feel free to reopen.
