### ISSUE TITLE
[linter] missing flag to not use ci_exclusions files.

### ISSUE THREAD

**Issue by williexu** [Azure/azure-cli-dev-tools#43]
`azdev linter` is missing a `--ci` flag. By default, I believe it is running in ci mode, which means there is no longer a way to run the linter and ignore the exclusions made for the ci.

**Comment by tjprescott** [comment]
The linter checks for the presence of the CI environment variable to determine whether to apply ci_exclusions. So by default it would not apply ci_exclusions. Of course, that raises the problem that you can't run it locally with exclusions unless you set the env variable. I'll add the flag back in. Thanks @williexu
