### ISSUE TITLE
Azdev doesn't detect virtual environment when using conda

### ISSUE THREAD

**Issue by glGarg** [Azure/azure-cli-dev-tools#44]
I installed azdev on a virtual environment on a Windows machine but when I ran azdev setup I get the following output:

F:\workspace>azdev setup -c azure-cli
This command can only be run from an active virtual environment.

I double checked to make sure the environment was activated and the path to the repo that I provided was correct. I tried running pip freeze in the virtual environment and it showed azdev-0.0.2 as installed. I also made sure that azdev wasn't installed outside the virtual environment so that when we ran the command it wasn't getting confused with some other install of azdev.

Our current workaround for this is to use scripts/dev_setup.py instead.

Thanks!

Spandan

**Comment by tjprescott** [comment]
Hi @glGarg, when your virtual environment is activated, if you `echo $VIRTUAL_ENV` do you get any output? The virtual environment is detected by the appropriate environment variable. Can you run `env` locally and find out, when your virtual env is active, which environment variable contains the path to your venv? If Conda simply uses a different variable, that will be a simple fix.

**Comment by test-account101** [comment]
I get the following output:
(F:\workspace> echo $VIRTUAL_ENV
$VIRTUAL_ENV

**Comment by glGarg** [comment]
I get the following output:
(F:\workspace>echo $VIRTUAL_ENV
$VIRTUAL_ENV

**Comment by tjprescott** [comment]
Ah, sorry, I thought you were on Linux. Okay, so then with your virtual environment active, please run `set` which will list out all of your environment variables. Find whichever one shows the path to your virtual environment and let me know the name. Azdev looks for `VIRTUAL_ENV` but I'm guessing it is different in your situation.

**Comment by tjprescott** [comment]
Based on offline discussions, it looks like `CONDA_PROMPT_MODIFIER` and `CONDA_PREFIX` describe the virtual environment.
