### ISSUE TITLE
Azdev does not properly install / copy pylintrc config file.

### ISSUE THREAD

**Issue by irvokopo** [Azure/azure-cli-dev-tools#441]
Hello,

We are developing an azure CLI extension and we are seeing this issue again: [Azdev does not properly install / copy pylintrc config file.](https://github.com/Azure/azure-cli-dev-tools/issues/21)
with the latest 0.1.65 release.

Any help would be appreciated please,
Iris

**Comment by wangzelin007** [comment]
Hi @irvokopo 
Can you provide detailed error log?

**Comment by irvokopo** [comment]
Hi @wangzelin007 - these changes fix our issue - thank you very much for your help!
