### ISSUE TITLE
C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe: No module named pytest

### ISSUE THREAD

**Issue by adrianmo** [Azure/azure-cli-dev-tools#476]
I initially posted this as a comment of #474, but I'm creating a new issue since that one is closed and might not get much attention.

We have GitHub workflows running every day and testing our extension in Windows, Mac, and Ubuntu. Starting on September 13th, Windows builds started to fail with the error message below when running `azdev test <extension_dir> --series`. 

```
=============
| Run Tests |
=============

=====================
| Discovering Tests |
=====================

test index created: C:\Users\runneradmin\.azdev\env_config\a\...\env\test_index\latest.json

Test on modules: <extension_name>

The tests are set to run against current profile "latest"
C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe: No module named pytest
Error: Process completed with exit code 1.
```

Looking deeper into it, we realized that this started to happen after `azdev` was updated to v0.1.79. So we downgraded to v0.1.77 and the builds started to work fine again, so I guess a bug was introduced in the latest release...

Based on the logs, I can see that `azdev` is trying to use the global Python interpreter at `C:\hostedtoolcache\windows\Python\3.11.9\x64\python.exe` instead of the one in the virtual environment, which is properly activated before running the command. 

Please let me know if you need any help reproducing the issue.

**Comment by AllyW** [comment]
Hi @adrianmo , thanks for reporting this issue. We've fixed it on Sept. 19 and please install the latest version 0.1.80 to see if it works now.

**Comment by adrianmo** [comment]
Hey @AllyW, thanks for the quick turnaround! I've verified that the issue is gone with the latest 0.1.80 release. I'm closing this issue as resolved, thanks again!
