### ISSUE TITLE
loading help emits out an error

### ISSUE THREAD

**Issue by yugangw-msft** [Azure/azure-cli-dev-tools#49]
Notes:
1. Only repro'd if I have used "azdev" to set up everything
2. Not repro'd if I run regular "python scripts\dev_setup.py"
3. If there are examples, the help seemingly works fine

```bash
(env) C:\sdk\azure-cli>az mysql -h
C:\sdk\azure-cli\env\lib\site-packages\knack\help_files.py:14: YAMLLoadWarning:
  *** Calling yaml.load() without Loader=... is deprecated.
  *** The default Loader is unsafe.
  *** Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(helps[delimiters])
```

**Comment by tjprescott** [comment]
I have seen this as well. I believe it is related to pyyaml.

**Comment by tjprescott** [comment]
What version of knack do you have when you run `pip --list`?

**Comment by tjprescott** [comment]
This occurs because the core CLI allows beta version of PyYAML and is caused by PyYAML 5.1b3.

**Comment by tjprescott** [comment]
This would happen whether you use azdev or dev_setup.py. https://github.com/Azure/azure-cli/pull/8696 returns the CLI to using the non-beta PyYAML, which will prevent these warnings.
