### ISSUE TITLE
No CLI Packages Installed After Azdev Setup

### ISSUE THREAD

**Issue by glGarg** [Azure/azure-cli-dev-tools#57]
Hi,

I was having issues when running azdev setup on Windows. I followed all the steps outlined in the Readme. When I run azdev setup -c <PathToClone>, the process takes less than a minute. And when I do a pip freeze later, the output doesn't contain any cli packages.

I am currently running on Windows and using Python 3.6.5.

Please let me know if I should give any other information.

Thanks!

Spandan

**Comment by tjprescott** [comment]
Unable to reproduce. Closing.
