### ISSUE TITLE
azdev setup Failed with NoneType Error

### ISSUE THREAD

**Issue by ziwa-msft** [Azure/azure-cli-dev-tools#72]
I followed the instruction for setting up dev env. Everything worked until the last step where I got the below error (running python27):

PS F:\azure-cli\src\azure-cli> azdev setup
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\PYTHON27\SCRIPTS\azdev.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\azdev\__main__.py", line 40, in main
    config_dir=get_azdev_config_dir())
  File "c:\python27\lib\site-packages\azdev\utilities\config.py", line 24, in get_azdev_config_dir
    _, env_name = os.path.splitdrive(get_env_path())
  File "c:\python27\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()

**Comment by tjprescott** [comment]
Thanks @ziwa-msft I'll take a look. It looks like you are running Powershell with Python 2.7?

**Comment by tjprescott** [comment]
Also, what version of azdev are you running? `azdev --version`?

**Comment by ziwa-msft** [comment]
azdev --version returns the same error at line env_name = os.path.splitdrive(get_env_path().

Is PowerShell not recommended here? I tried cmd and bash and got the same result

**Comment by tjprescott** [comment]
Powershell is never recommended for CLI work. What steps did you use to install azdev? What path is your virtual environment created in?

**Comment by ziwa-msft** [comment]
I just followed the guide to do pip install azdev. I ran the python -m virtualenv env cmd in my azure cli root.

Can you point me to the recommended practice if Powershell is not okay then? I merely followed the instructions and there isn't any mention of what tools/environment path to use

**Comment by tjprescott** [comment]
With your virtual environment active, what do you get if you run `$env:virtual_env`?

**Comment by tjprescott** [comment]
I installed azdev and ran through the setup with Powershell without issue, so I'm trying to identify the reason your setup isn't work. The reason we don't recommend PS for CLI work is because people experience more PS-specific issues related to special characters than on bash or Linux. There's no reason you *can't* use it if you prefer it

**Comment by ziwa-msft** [comment]
Looks like the virtual env is not set up correctlu. When I try to get the virtual_env variable I got nothing. See below for output:

PS C:\Users\ziwa> F:
PS F:\> cd .\azure-cli
PS F:\azure-cli> python -m virtualenv env
New python executable in F:\azure-cli\env\Scripts\python.exe
Installing setuptools, pip, wheel...
done.
PS F:\azure-cli> env\scripts\activate.bat
PS F:\azure-cli> $env:virtual_env
PS F:\azure-cli> pip install azdev
...

**Comment by ziwa-msft** [comment]
I followed this doc: https://github.com/Azure/azure-cli-dev-tools

How can I verify virtual env is working?

**Comment by tjprescott** [comment]
Ah, thank you for that @ziwa-msft. For PS, you should not use activate.bat--that's for Windows CMD. For Powershell, there should be a PS-specific script in that folder. If you use `env\scripts\activate[Tab][Tab]` it should autocomplete to the Powershell script.  Then you should see something like: 
`(env) PS F:\azure-cli` for your prompt and you'll know your virtual environment is active. I'll update the documentation accordingly. Please confirm that this works for you.

**Comment by ziwa-msft** [comment]
Thanks for the help! It worked after I used activate.ps1

**Comment by tjprescott** [comment]
I updated the docs. Thanks for the report!
