### ISSUE TITLE
pytest~=3.6.0, but pytest-xdist has pytest>=4.4.0

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-cli-dev-tools#87]
Using `pipenv` to grab the latest azdev==0.0.5, it fails with `Could not find a version that matches pytest>=4.4.0,~=3.6.0`. I ran `pipenv graph` and I see the problem:

```
  - pytest [required: ~=3.6.0, installed: 3.6.4]

  - pytest-xdist [required: Any, installed: 1.28.0]
    - pytest [required: >=4.4.0, installed: 3.6.4]
```

**Comment by tjprescott** [comment]
This has been fixed on the master branch. It just hasn't been released yet.

**Comment by tjprescott** [comment]
https://github.com/Azure/azure-cli-dev-tools/pull/79
