### ISSUE TITLE
min_core for `az extension create` should actually be 2.0.67

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-cli-dev-tools#90]
Currently it puts 2.0.66 and if you run `azdev setup -r …`, installing the latest public version of the CLI, your created extensions/modules will fail because of the missing `is_preview` kwarg.

**Comment by tjprescott** [comment]
The temporary fix is to remove the final two lines from the generated `commands.py` file that uses the, as-yet-unpublished `is_preview` flag.

**Comment by ctaggart** [comment]
Thanks for the heads up.

**Comment by tjprescott** [comment]
It will also work without removing `is_preview` if you run azdev setup with `-c` to do a dev install of the CLI.
