### ISSUE TITLE
trouble using `azdev setup` to develop an extension

### ISSUE THREAD

**Issue by ctaggart** [Azure/azure-cli-dev-tools#92]
I'm a bit confused on how to run `azdev setup` to set up development on an extension [as documented](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/authoring.md#developing).

I forked the `azure-keyvault-cli-extension` and added a Pipfile.
``` ps1
git clone git@github.com:ctaggart/azure-keyvault-cli-extension.git
cd .\azure-keyvault-cli-extension\
git checkout pipenv
# create virtualenv
pipenv install --ignore-pipfile
# use virtualenv
pipenv shell
# this is where I am confused
azdev setup -r $PWD -e keyvault-preview
```

> If you are only developing your extension run: azdev setup -r <PATH> -e <NAME> where PATH is the path to the local git folder your extension resides in and NAME is the name of your extension.

For `<PATH>` I'm using `$PWD` since the code is the current directory. For `<NAME>`, I'm using the name found in `setup.py`.

It errors out for me with:
```
PS C:\Users\taggac\tmp\azure-keyvault-cli-extension> azdev setup -r "$PWD" -e keyvault-preview

=======================
| Azure CLI Dev Setup |
=======================

Azure CLI:
    PyPI

Azure CLI extension repos:
    C:\Users\taggac\tmp\azure-keyvault-cli-extension
The following extensions were not found. Ensure you have added the repo using `--repo/-r PATH`.
    keyvault-preview
```

cc @tjprescott

**Comment by tjprescott** [comment]
> \# this is where I am confused
> azdev setup -r $PWD -e keyvault-preview

Instead, try this:
`azdev setup -r $PWD`

This will allow the setup to complete.  Then you can run `azdev extension list -otable` to see all possible extensions you could install based on your dev repo sources and which are and are not installed. You will see that the name it is expecting is `azure-keyvault-cli-extension`.  So, you could update your script like so:

`azdev setup -r $PWD -e azure-keyvault-cli-extension`

If that doesn't work for you, please open.
