### ISSUE TITLE
azdev test MODULE does not work on Windows

### ISSUE THREAD

**Issue by swbae31** [Azure/azure-cli-dev-tools#94]
## Describe the bug

**Command Name**
azdev test MODULE

ex) azdev test vm

**Errors:**

azdev test vm

| Run Tests |

The tests are set to run against current profile latest.

| Discovering Tests |

list index out of range
Traceback (most recent call last):
  File "c:\users\subae\desktop\azure-cli\env\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\subae\desktop\azure-cli\env\lib\site-packages\knack\invocation.py", line 208, in execute
    cmd_result = parsed_args.func(params)
  File "c:\users\subae\desktop\azure-cli\env\lib\site-packages\knack\commands.py", line 139, in __call__
    return self.handler(*args, **kwargs)
  File "c:\users\subae\desktop\azure-cli\env\lib\site-packages\knack\commands.py", line 246, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "c:\users\subae\desktop\azure-cli\env\lib\site-packages\azdev\operations\tests\__init__.py", line 43, in run_tests
    test_index = _get_test_index(profile, discover)
  File "c:\users\subae\desktop\azure-cli\env\lib\site-packages\azdev\operations\tests\__init__.py", line 300, in _get_test_index
    test_index = _discover_tests(profile)
  File "c:\users\subae\desktop\azure-cli\env\lib\site-packages\azdev\operations\tests\__init__.py", line 223, in _discover_tests
    filepath = glob.glob(os.path.join(mod_path, glob_pattern))[0]
IndexError: list index out of range

## To Reproduce:

On Windows Powershell, clone and set up the azure-cli repository. Run

azdev test vm

## Expected Behavior

Tests discovered and run.

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.7.2
Shell: python.exe

azure-cli 2.0.67

```

**Comment by tjprescott** [comment]
What do you get when you run `azdev --version`?

**Comment by rajivnandivada** [comment]
I have the same issue. azdev --version returns 0.0.6. Additionally style and linter checks are also not working.

**Comment by tjprescott** [comment]
Please provide the output of `pip list`.

**Comment by rajivnandivada** [comment]
Here you go. Thanks.
Package                               Version   Location                                           
------------------------------------- --------- ---------------------------------------------------
adal                                  1.2.1     
antlr4-python3-runtime                4.7.2     
apipkg                                1.5       
applicationinsights                   0.11.9    
argcomplete                           1.10.0    
asn1crypto                            0.24.0    
astroid                               2.2.5     
atomicwrites                          1.3.0     
attrs                                 19.1.0    
azdev                                 0.0.6     
azure-batch                           6.0.1     
azure-cli                             2.0.67    e:\src\azure-cli.rajivnan.2\src\azure-cli          
azure-cli-command-modules-nspkg       2.0.2     
azure-cli-core                        2.0.67    e:\src\azure-cli.rajivnan.2\src\azure-cli-core     
azure-cli-nspkg                       3.0.3     e:\src\azure-cli.rajivnan.2\src\azure-cli-nspkg    
azure-cli-telemetry                   1.0.2     e:\src\azure-cli.rajivnan.2\src\azure-cli-telemetry
azure-cli-testsdk                     0.2.4     e:\src\azure-cli.rajivnan.2\src\azure-cli-testsdk  
azure-common                          1.1.23    
azure-cosmos                          3.1.0     
azure-datalake-store                  0.0.45    
azure-devtools                        1.0.0     
azure-functions-devops-build          0.0.22    
azure-graphrbac                       0.60.0    
azure-keyvault                        1.1.0     
azure-mgmt-advisor                    2.0.1     
azure-mgmt-applicationinsights        0.1.1     
azure-mgmt-authorization              0.50.0    
azure-mgmt-batch                      6.0.0     
azure-mgmt-batchai                    2.0.0     
azure-mgmt-billing                    0.2.0     
azure-mgmt-botservice                 0.2.0     
azure-mgmt-cdn                        3.1.0     
azure-mgmt-cognitiveservices          3.0.0     
azure-mgmt-compute                    5.0.0     
azure-mgmt-consumption                2.0.0     
azure-mgmt-containerinstance          1.5.0     
azure-mgmt-containerregistry          2.8.0     
azure-mgmt-containerservice           5.3.0     
azure-mgmt-cosmosdb                   0.5.2     
azure-mgmt-datalake-analytics         0.2.1     
azure-mgmt-datalake-nspkg             3.0.1     
azure-mgmt-datalake-store             0.5.0     
azure-mgmt-datamigration              0.1.0     
azure-mgmt-deploymentmanager          0.1.0     
azure-mgmt-devtestlabs                2.2.0     
azure-mgmt-dns                        2.1.0     
azure-mgmt-eventgrid                  2.2.0     
azure-mgmt-eventhub                   2.6.0     
azure-mgmt-hdinsight                  0.2.1     
azure-mgmt-imagebuilder               0.2.1     
azure-mgmt-iotcentral                 1.0.0     
azure-mgmt-iothub                     0.8.2     
azure-mgmt-iothubprovisioningservices 0.2.0     
azure-mgmt-keyvault                   1.1.0     
azure-mgmt-kusto                      0.3.0     
azure-mgmt-loganalytics               0.2.0     
azure-mgmt-managedservices            0.1.0     
azure-mgmt-managementgroups           0.2.0     
azure-mgmt-maps                       0.1.0     
azure-mgmt-marketplaceordering        0.2.1     
azure-mgmt-media                      1.1.1     
azure-mgmt-monitor                    0.5.2     
azure-mgmt-msi                        0.2.0     
azure-mgmt-network                    3.0.0     
azure-mgmt-nspkg                      3.0.2     
azure-mgmt-policyinsights             0.3.1     
azure-mgmt-privatedns                 0.1.0     
azure-mgmt-rdbms                      1.9.0     
azure-mgmt-recoveryservices           0.1.1     
azure-mgmt-recoveryservicesbackup     0.1.2     
azure-mgmt-redis                      6.0.0     
azure-mgmt-relay                      0.1.0     
azure-mgmt-reservations               0.3.2     
azure-mgmt-resource                   2.2.0     
azure-mgmt-search                     2.1.0     
azure-mgmt-security                   0.1.0     
azure-mgmt-servicebus                 0.6.0     
azure-mgmt-servicefabric              0.2.0     
azure-mgmt-signalr                    0.1.1     
azure-mgmt-sql                        0.12.0    
azure-mgmt-sqlvirtualmachine          0.3.0     
azure-mgmt-storage                    3.3.0     
azure-mgmt-trafficmanager             0.51.0    
azure-mgmt-web                        0.42.0    
azure-multiapi-storage                0.2.4     
azure-nspkg                           3.0.2     
azure-storage-blob                    1.5.0     
azure-storage-common                  1.4.2     
bcrypt                                3.1.7     
certifi                               2019.6.16 
cffi                                  1.12.3    
chardet                               3.0.4     
colorama                              0.4.1     
ConfigArgParse                        0.14.0    
cryptography                          2.7       
docutils                              0.14      
entrypoints                           0.3       
execnet                               1.6.0     
fabric                                2.4.0     
filelock                              3.0.12    
flake8                                3.7.7     
gitdb2                                2.0.5     
GitPython                             2.1.11    
humanfriendly                         4.18      
idna                                  2.8       
importlib-metadata                    0.18      
invoke                                1.2.0     
isodate                               0.6.0     
isort                                 4.3.20    
Jinja2                                2.10.1    
jmespath                              0.9.4     
knack                                 0.6.2     
lazy-object-proxy                     1.4.1     
MarkupSafe                            1.1.1     
mccabe                                0.6.1     
mock                                  2.0.0     
more-itertools                        7.0.0     
msrest                                0.6.8     
msrestazure                           0.6.1     
multidict                             4.5.2     
oauthlib                              3.0.1     
packaging                             19.0      
paramiko                              2.6.0     
pbr                                   5.3.1     
pip                                   19.1.1    
pluggy                                0.12.0    
portalocker                           1.4.0     
prompt-toolkit                        1.0.16    
psutil                                5.6.3     
py                                    1.8.0     
pycodestyle                           2.5.0     
pycparser                             2.19      
pydocumentdb                          2.3.3     
pyflakes                              2.1.1     
Pygments                              2.4.2     
PyJWT                                 1.7.1     
pylint                                2.3.0     
PyNaCl                                1.3.0     
pyOpenSSL                             19.0.0    
pyparsing                             2.4.0     
pypiwin32                             223       
pyreadline                            2.1       
pytest                                4.4.2     
pytest-forked                         1.0.2     
pytest-xdist                          1.29.0    
python-dateutil                       2.8.0     
pytz                                  2019.1    
pywin32                               224       
PyYAML                                5.1.1     
requests                              2.22.0    
requests-oauthlib                     1.2.0     
scp                                   0.13.2    
setuptools                            40.0.0    
six                                   1.12.0    
smmap2                                2.0.5     
sshtunnel                             0.1.5     
tabulate                              0.8.3     
toml                                  0.10.0    
tox                                   3.13.0    
typed-ast                             1.4.0     
urllib3                               1.24.2    
vcrpy                                 2.0.1     
virtualenv                            16.6.1    
vsts                                  0.1.25    
vsts-cd-manager                       1.0.2     
wcwidth                               0.1.7     
websocket-client                      0.56.0    
wheel                                 0.30.0    
wrapt                                 1.11.2    
xmltodict                             0.12.0    
yarl                                  1.3.0     
zipp                                  0.5.1

**Comment by tjprescott** [comment]
azdev version 0.0.6 is not compatible with the current dev branch of the CLI. You would need to do a dev installation of azdev until 0.1.0 is released.

**Comment by rajivnandivada** [comment]
Where can I still it from? Thanks.

**Comment by tjprescott** [comment]
Clone this repo and install with `pip install -e azure-cli-dev-tools`

**Comment by rajivnandivada** [comment]
That fixed the issue. Although the version installed is 0.0.7. Thanks.
