### ISSUE TITLE
azdev test not working for unittest.TestCase

### ISSUE THREAD

**Issue by limingu** [Azure/azure-cli-dev-tools#96]
(env) C:\Users\limgu\workspace\azure-cli>azdev test test_validate_source_uri

=============
| Run Tests |
=============

The tests are set to run against current profile latest.

test index found: C:\Users\limgu\.azdev\env_config\Users\limgu\workspace\env\test_index\latest.json

TESTS: test_validate_source_uri

====================================================================================== test session starts =======================================================================================
platform win32 -- Python 3.6.8, pytest-4.4.2, py-1.8.0, pluggy-0.12.0
rootdir: C:\Users\limgu\workspace\azure-cli
plugins: forked-1.0.2, xdist-1.29.0
gw0 [0] / gw1 [0] / gw2 [0] / gw3 [0] / gw4 [0] / gw5 [0] / gw6 [0] / gw7 [0] / gw8 [0] / gw9 [0] / gw10 [0] / gw11 [0]

------------------------------------------------ generated xml file: C:\Users\limgu\.azdev\env_config\Users\limgu\workspace\env\test_results.xml -------------------------------------------------
================================================================================== no tests ran in 1.80 seconds ==================================================================================

 Results
=========

Time: 1.800 sec Tests: 0        Skipped: None   Failures: 0     Errors: 0

**Comment by tjprescott** [comment]
Since we got this working and I'm not sure how to repro this, I will close for now.
